name: Pipeline API

on:
  # Evento que dispara o pipeline
  push:
  
    # Branch que dispara o pipeline
    branches:
      - master

    # Arquivos que estamos monitorando para iniciar o pipeline
    paths:
      - 'api/**'
      - '.github/workflows/*-api.yml'
      - './package.json'
      - './Procfile'

# Variaveis de ambiente global
env:

  # Pasta da nossa aplicacao
  APP_DIR: api

# Tarefas que serão executadas no pipeline
jobs:
  
  # Tarefa responsavel pelo Build e Test
  CI:

    # Instancia que iremos executar as tarefas
    runs-on: ubuntu-latest

    # Diretorio que iremos executar o build e os testes
    defaults:
      run:
        working-directory: ${{env.APP_DIR}}

    # Passos que serao executados nesta tarefa
    steps:

    # Fazer o checkout / pull do repositorio
    - name: Checkout do repositorio
      uses: actions/checkout@v3

    # Baixa e configurar o Node.js
    - name: Configuracao Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    # Instalar os modulos no projeto
    - name: Instalar modulos
      run: npm install

    # Executar os testes no projeto
    - name: Executar testes
      run: npm test
